AllCops:
  # Your Ruby version
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  # Exclude what you need here.
  Exclude:
    - db/**/*
    - config/**/*
    - tmp/**/*
    - spec/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
